### PR TITLE
Rename UtTestCase #519

### LINKED ISSUE #519: Rename UtTestCase
**Description**

We have `UtTestCase` class consisting of several `UtExecution`s. It encapsulates all tests scenarios related to single method test generation. It is confusing because usually "test case" means one test scenario, not many.

The suggestion is to rename `UtTestCase` into something more clear.
Options:
- UtMethodTestSet
- UtTestCases
- UtMethodTestSuite

**Context**

`UtTestCase` is our API class representing generated test scenarios for one method under analysis.

### PR DESCRIPTION
**Pull request by sergeypospelov**
# Description

- Renamed `UtTestCase` class to `UtMethodTestSet`.
- Also renamed all related local variables and functions to `...testSet...`.
- Along with this, renamed `UtValueTestCase` to `UtMethodValueTestSet`. FYI: it's only used in our tests.

Fixes #519

## Type of Change

- Refactoring (typos and non-functional changes) 

# Checklist:

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] No new warnings
- [x] All tests pass locally with my changes

### CODE REVIEW

**Comment by IdeaSeeker** [comment]
Also:
- examples/SummaryTestCaseGeneratorTest.kt:100
- org/utbot/framework/codegen/model/constructor/tree/CgTestClassConstructor.kt:53
- org/utbot/examples/UtModelTestCaseChecker.kt:96
- org/utbot/examples/UtValueTestCaseChecker.kt:2295

**Comment by IdeaSeeker** [comment]
Also:
- org/utbot/examples/UtValueTestCaseChecker.kt:2339
- org/utbot/examples/UtValueTestCaseChecker.kt:2479
- org/utbot/framework/plugin/api/FuzzerTestCaseGeneratorTest.kt:18

**Comment by sergeypospelov** [comment]
Looks like
> * org/utbot/contest/Contest.kt:336

shouldn't be renamed

**Comment by IdeaSeeker** [comment]
Also:
- org/utbot/cli/BunchTestGeneratorCommand.kt:107
- org/utbot/cli/GenerateTestsCommand.kt:105
- org.utbot.cli.GenerateTestsAbstractCommand#generateTestSets
- org/utbot/framework/coverage/CoverageCalculator.kt:143
- org/utbot/intellij/plugin/generator/CodeGenerationController.kt:98

**Review by IdeaSeeker — CHANGES_REQUESTED** [review]
Also:
- org/utbot/external/api/UtBotJavaApi.kt:153 (with comment)
- org/utbot/external/api/UtBotJavaApi.kt:105
- (?) org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt:1365

**Comment by sergeypospelov** [comment]
> * (?) org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt:1365
> * (?) org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt:1312

Looks like these uses of "case" are correct.

**Review by IdeaSeeker — APPROVED** [review]

**Pull request merged**
