### PR TITLE
Self-documenting settings template

### LINKED ISSUE #1412: Self-documenting settings template
**Description**

At the moment we don't provide settings.properties file for users. Moreover there is no documentation for this file, and we don't create it by default.

**Expected behavior**

As soon as the only source of knowledge is our sourcecode (namely **UtSettings.kt**) we should generate _settings.properties as resource file_ inside plugin archive and provide settings template in user's **{home}/.utbot/settings.properties** with all default values and documentation from corresponding sourcecode comments.

The generation should be part of "IntelliJ" Gradle task

**Note**: we shouldn't re-write settings.properties if the file is presented with some custom (not default) user-defined values.

### PR DESCRIPTION
**Pull request by Vassiliy-Kudryashov**
# Description

1. There is new helper to be used from Gradle task. It converts **UtSettings.kt** to resource file **settings.properties**.
So, actual state of UtSettings.kt (properties, defauls, relevant documentation comments) will allways be converted to bundled resource file we publish along with the plugin as top-level entry inside **utbot-intellij-{version}.jar** file. 
_Note, the template contains commented lines only so we free to change our hardcoded defaults later and re-write outdated template with new one until it's customized by user._

2. Just after IDE start (namely when plugin loads its settings) we check if settings.properties is presented in user's local file system as **{home}/.utbot/settings.properties**:
- If not we create it from the resource template together with the folder is need. 
- If file already exists we copy resource template **only if there are no custom (provided by user) values** inside to persist existing users' configuration "as is".

Fixes #1412 

## Type of Change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

## Manual Scenarios

**Scenario 1**
- Delete {home}/.utbot folder if exists.
- Start IDE, wait for project loading.
The folder {home}/.utbot should be created automatically, for Windows it also should be marked as "hidden file".
There should be template file settings.properties inside. 
If you delete the file it should appear again after IDE restart.

**Scenario 2**
- Clear the file {home}/.utbot/settings.properties, leave just one line inside: _disableCoroutinesDebug=true_
- Start IDE, wait for project loading.
As soon as property file contains defaults, it should be re-writen with template.

**Scenario 3**
- Clear the file {home}/.utbot/settings.properties, leave just one line inside: _disableCoroutinesDebug=false_
- Start IDE, wait for project loading.
- As soon as property file contains custom value, it should stay as is.

# Checklist (remove irrelevant options):

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [x] New documentation is provided or existed one is altered
- [x] No new warnings

### CODE REVIEW

**Comment by alisevych** [comment]
Some ideas from our discussion with @Vassiliy-Kudryashov and @olganaumenko:

1. Create settings.properties.template near to settings.properties - and recreate it every time the plugin is installed.
That can be useful to have the template with the current version of settings.

2. Select the most important settings. Which can be suggested first to the user. 
They can be listed above all others. And described separately in docs.

**Review by EgorkaKulikov — APPROVED** [review]
LNVGTM, but it seems to be our way now. Discussed verbally with Vasya. Some potential mines are going to be removed in further implementations. 
Also I suggest to test it in branch before merge.

**Comment by alisevych** [comment]
@Vassiliy-Kudryashov Please check:
the changed settings are not applied (or may be not parsed)

**To reproduce**

1. Removed existing settings.properties file 
2. Installed [build from this branch](https://github.com/UnitTestBot/UTBotJava/actions/runs/3566250883)
3. Restarted IDE
4. Opened generated settings.properties file
5. Uncommented the line with `utBotGenerationTimeoutInMillis` and changed value to `1000`
6. Restarted IDE once more
7. Open UnitTestBot dialog

**Expected behavior**

Test generation timeout should be 1 sec

**Actual behavior**

Default test generation timeout is applied - 60 sec

**Additional context**

The same issue is when executing runIde task.
The issue is not reproducing in main - the change of this setting is applied.

**Comment by alisevych** [comment]
@Vassiliy-Kudryashov 
Also the usability question:
- after UnitTestBot plugin installation there are 2 IDE restarts needed to apply new settings:
1. To generate `settings.properties` template
2. To apply changes in properties-file
Could we consider some improvements for this? Probably a discussion would help?

**Comment by alisevych** [comment]
@Vassiliy-Kudryashov @Domonion 
Could you please advise if we can log the settings that differ from default ones?
One the step of IDE start or when the test run is performed.
That can explain some issues and help with reproducing customer's bugs.

**Pull request merged**
