### PR TITLE
Add a doc about the Custom Javadoc Tags feature

### PR DESCRIPTION
**Pull request by onewhl**
# Description

Add a doc about the Custom Javadoc Tags feature.

## Type of Change

- New documentation 

# Checklist (remove irrelevant options):

- [x] New documentation is provided or existed one is altered
- [x] All tests pass locally with my changes

### CODE REVIEW

**Comment by olganaumenko** [comment]
@onewhl, please find the screenshots below :)


settings-example


settings-example-2


Screenshot (28)


Screenshot (29)


Screenshot (27)


Screenshot (26)


Screenshot (32)


Screenshot (30)


Screenshot (33)


Screenshot (31)

**Comment by onewhl** [comment]
@korifey there are some screenshots and I'm not sure if it's ok to add them to repository. Where can we store them?

**Comment by amandelpie** [comment]
> @korifey there are some screenshots and I'm not sure if it's ok to add them to repository. Where can we store them?

IMHO, we could a subfolder images in docs and them there if they are enough small

**Comment by onewhl** [comment]
@amandelpie each image is about 50Kb. It would be awesome to store images on some server and add links to the images to the doc. So, they would be rendered in markdown correctly and won't occupy space in the repository.

**Review by amandelpie — APPROVED** [review]

**Comment by amandelpie** [comment]
@korifey could please have a look and approve

**Comment by amandelpie** [comment]
@korifey please have a look, need to merge it

**Pull request merged**
