### PR TITLE
Fix python coverage database bug with access to database directory

### LINKED ISSUE #1478: Python test generation error
**Description**

Python test generation error is showing for quite simple python functions, including examples on [utbot.org](https://www.utbot.org/demo/?language=Python)

**To Reproduce**

1. Install [one of the latest plugin builds from main ](https://github.com/UnitTestBot/UTBotJava/actions/runs/3637743780) in IntelliJ Idea 2022.2.3
2. Install Python plugin from MarketPlace
3. Create a Python project 
4. Add the following code to it:

```python
def print_hi(name):
    # Use a breakpoint in the code line below to debug your script.
    print(f'Hi, {name}')  # Press Ctrl+F8 to toggle the breakpoint.

def div(a, b):
    return a / b

# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    print_hi('PyCharm')
```
5. Press Alt+Shift+U in code
6. Select both functions and generate tests
7. Agree to install suggested requirements
8. Make 5-6 steps once again

**Expected behavior**

Tests are supposed to be generated.

**Actual behavior**

An error dialog is show with the following test:
`Cannot create tests for the following functions: print_hi, div`

**Visual proofs (screenshots, logs, images)**

image

**Environment**

Windows 10 Pro
IntelliJ IDEA 2022.2.3 (not latest)

**Additional context**

Same with `pytest` or increased timeouts or manually create test sources root.
`Generating tests...` is displayed in inline progress.

### PR DESCRIPTION
**Pull request by tamarinvs19**
# Description

Fix bug with database path in python module `coverage`. Now we create database in temporary directory with other python files.

__Note:__ See #1542

Fixes #1478

## Type of Change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

## Manual Scenario 

See https://github.com/UnitTestBot/UTBotJava/issues/1478 steps 1-8 with plugin from [this build](https://github.com/UnitTestBot/UTBotJava/actions/runs/3739306191)

Expected result: generated tests, for example:

```python
import sys
sys.path.append('..')
import builtins
import types
import sample
import unittest


class TestTopLevelFunctions(unittest.TestCase):
    # region Test suites for executable sample.print_hi
    
    # region
    
    def test_print_hi(self):
        actual = sample.print_hi((1 << 100))
        
        self.assertEqual(None, actual)
    
    def test_print_hi_throws_t(self):
        sample.print_hi(str(b'\xf0\xa3\x91\x96', 'utf-8'))
        
        # raises builtins.UnicodeEncodeError
    # endregion
    
    # endregion
    
    # region Test suites for executable sample.div
    
    # region
    
    def test_div(self):
        actual = sample.div(1, 1)
        
        self.assertEqual(1.0, actual)
    # endregion
    
    # endregion
```

# Checklist (remove irrelevant options):

_This is the author self-check list_

- [x] The change followed the style guidelines of the UTBot project
- [x] Self-review of the code is passed
- [x] The change contains enough commentaries, particularly in hard-to-understand areas
- [ ] New documentation is provided or existed one is altered
- [x] No new warnings
- [ ] New tests have been added
- [x] All tests pass locally with my changes

### CODE REVIEW

**Comment by tyuldashev** [comment]
Unfortunately it still doesn't work, it looks the same as before - just hangs during generation. It seems that this version has no verbose logging, so I'm not sure if it's the same error (problem with sql-light db file) or another one.

**Comment by tyuldashev** [comment]
Errors from the log:
```
2022-12-20 13:26:26,441 [ 133425]   INFO - STDOUT - | UtBot - PythonEvaluation          | Start evaluation div with [1, 0.0]
2022-12-20 13:26:26,441 [ 133425]   INFO - STDOUT - | UtBot - PythonEvaluation          | Evaluation with arguments [1, 0.0] finished; Exit value: 1; Stdout: ; Stderr:   File "C:\Users\T00814~1\AppData\Local\Temp\UTBot\python-test-generation-0368468099035101053\51_run_div.py", line 8
2022-12-20 13:26:26,443 [ 133427]   INFO - STDOUT -     run_calculate_function_value('C:\Users\T00814~1\AppData\Local\Temp\UTBot\python-test-generation-0368468099035101053\50_coverage_db_div',
2022-12-20 13:26:26,443 [ 133427]   INFO - STDOUT -                                                                                                                                            ^
2022-12-20 13:26:26,443 [ 133427]   INFO - STDOUT - SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
2022-12-20 13:26:26,446 [ 133430]   INFO - STDOUT - | UtBot - PythonEvaluation          | Start evaluation div with [4294967296, 0.0]
2022-12-20 13:26:26,448 [ 133432]   INFO - STDOUT - | UtBot - PythonEvaluation          | Evaluation with arguments [4294967296, 0.0] finished; Exit value: 1; Stdout: ; Stderr:   File "C:\Users\T00814~1\AppData\Local\Temp\UTBot\python-test-generation-0368468099035101053\54_run_div.py", line 8
2022-12-20 13:26:26,448 [ 133432]   INFO - STDOUT -     run_calculate_function_value('C:\Users\T00814~1\AppData\Local\Temp\UTBot\python-test-generation-0368468099035101053\53_coverage_db_div',
2022-12-20 13:26:26,448 [ 133432]   INFO - STDOUT -                                                                                                                                            ^
```

**Comment by tamarinvs19** [comment]
> Errors from the log:
> 
> ```
> 2022-12-20 13:26:26,441 [ 133425]   INFO - STDOUT - | UtBot - PythonEvaluation          | Start evaluation div with [1, 0.0]
> 2022-12-20 13:26:26,441 [ 133425]   INFO - STDOUT - | UtBot - PythonEvaluation          | Evaluation with arguments [1, 0.0] finished; Exit value: 1; Stdout: ; Stderr:   File "C:\Users\T00814~1\AppData\Local\Temp\UTBot\python-test-generation-0368468099035101053\51_run_div.py", line 8
> 2022-12-20 13:26:26,443 [ 133427]   INFO - STDOUT -     run_calculate_function_value('C:\Users\T00814~1\AppData\Local\Temp\UTBot\python-test-generation-0368468099035101053\50_coverage_db_div',
> 2022-12-20 13:26:26,443 [ 133427]   INFO - STDOUT -                                                                                                                                            ^
> 2022-12-20 13:26:26,443 [ 133427]   INFO - STDOUT - SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
> 2022-12-20 13:26:26,446 [ 133430]   INFO - STDOUT - | UtBot - PythonEvaluation          | Start evaluation div with [4294967296, 0.0]
> 2022-12-20 13:26:26,448 [ 133432]   INFO - STDOUT - | UtBot - PythonEvaluation          | Evaluation with arguments [4294967296, 0.0] finished; Exit value: 1; Stdout: ; Stderr:   File "C:\Users\T00814~1\AppData\Local\Temp\UTBot\python-test-generation-0368468099035101053\54_run_div.py", line 8
> 2022-12-20 13:26:26,448 [ 133432]   INFO - STDOUT -     run_calculate_function_value('C:\Users\T00814~1\AppData\Local\Temp\UTBot\python-test-generation-0368468099035101053\53_coverage_db_div',
> 2022-12-20 13:26:26,448 [ 133432]   INFO - STDOUT -                                                                                                                                            ^
> ```

I fixed this problem and start plugin building https://github.com/UnitTestBot/UTBotJava/actions/runs/3741539443

**Comment by tyuldashev** [comment]
It generates tests now, but not always can cleanup temp directories after execution:

```
java.nio.file.DirectoryNotEmptyException: C:\Users\T00814~1\AppData\Local\Temp\UTBot\python-test-generation-24799704321262215703
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:272)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
	at java.base/java.nio.file.Files.delete(Files.java:1152)
	at org.utbot.python.utils.TemporaryFileManager$setup$1.invoke(TemporaryFileManager.kt:15)
	at org.utbot.python.utils.TemporaryFileManager$setup$1.invoke(TemporaryFileManager.kt:15)
	at org.utbot.python.utils.Cleaner$addFunction$newClean$1.invoke(Cleaner.kt:9)
	at org.utbot.python.utils.Cleaner$addFunction$newClean$1.invoke(Cleaner.kt:8)
	at org.utbot.python.utils.Cleaner$addFunction$newClean$1.invoke(Cleaner.kt:10)
	at org.utbot.python.utils.Cleaner$addFunction$newClean$1.invoke(Cleaner.kt:8)
	at org.utbot.python.utils.Cleaner$addFunction$newClean$1.invoke(Cleaner.kt:10)
	at org.utbot.python.utils.Cleaner$addFunction$newClean$1.invoke(Cleaner.kt:8)
	at org.utbot.python.utils.Cleaner$addFunction$newClean$1.invoke(Cleaner.kt:10)
	at org.utbot.python.utils.Cleaner$addFunction$newClean$1.invoke(Cleaner.kt:8)
	at org.utbot.python.utils.Cleaner$addFunction$newClean$1.invoke(Cleaner.kt:10)
	at org.utbot.python.utils.Cleaner$addFunction$newClean$1.invoke(Cleaner.kt:8)
	at org.utbot.python.utils.Cleaner$addFunction$newClean$1.invoke(Cleaner.kt:10)
	at org.utbot.python.utils.Cleaner$addFunction$newClean$1.invoke(Cleaner.kt:8)
	at org.utbot.python.utils.Cleaner.doCleaning(Cleaner.kt:20)
	at org.utbot.python.PythonTestGenerationProcessor.processTestGeneration(PythonTestGenerationProcessor.kt:210)
	at org.utbot.python.PythonTestGenerationProcessor.processTestGeneration$default(PythonTestGenerationProcessor.kt:34)
	at org.utbot.intellij.plugin.language.python.PythonDialogProcessor$createTests$1.run(PythonDialogProcessor.kt:135)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by tamarinvs19** [comment]
New build with fixed the last bug https://github.com/UnitTestBot/UTBotJava/actions/runs/3747621097

**Comment by tamarinvs19** [comment]
New fix https://github.com/UnitTestBot/UTBotJava/actions/runs/3748217170

**Review by denis-fokin — APPROVED** [review]

**Pull request merged**
